#! /bin/sh

case "$1" in
    start)
        echo "starting aesdsocket"
        start-stop-daemon -S -n aesdsocket -a /usr/bin/aesdsocket -- -d
        ;;
    stop)
        echo "stopping aesdsocket"
        start-stop-daemon -K -n aesdsocket -a /usr/bin/aesdsocket
        ;;
    *)
        echo "Usage: $0 {start|stop}"
    exit 1
esac

exit 0
